name: Auto PR on branch push

on:
  push:
    branches:
      - 'feat/**'
      - 'chore/**'
      - 'fix/**'

jobs:
  open_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          title: "Auto PR: ${{ github.ref_name }}"
          body: |
            Automated PR for branch `${{ github.ref_name }}`.

            Please review docs/NEXT_MILESTONE.md for scope if applicable.
          branch: ${{ github.ref_name }}
          draft: false
